const projects = [
  {
    id:1,
    title: 'Horizon Banking App',
    client: 'Horizon Financial',
    category: 'Mobile',
    tags: ['React Native', 'FinTech', 'UX Design'],
    desc: 'A complete redesign of a legacy banking experience, resulting in a 42% increase in daily active users.',
    img: 'https://images.pexels.com/photos/4386321/pexels-photo-4386321.jpeg?auto=compress&cs=tinysrgb&w=800',
    featured: true,
  },
  {
    id:2,
    title: 'Verdant E-Commerce',
    client: 'Verdant Co.',
    category: 'Web',
    tags: ['Next.js', 'E-Commerce', 'Design System'],
    desc: 'An award-winning online storefront with a custom design system and seamless checkout flow.',
    img: 'https://images.pexels.com/photos/5632381/pexels-photo-5632381.jpeg?auto=compress&cs=tinysrgb&w=800',
    featured: true,
  },
  {
    id:3,
    title: 'Pulse Health Platform',
    client: 'Pulse Health',
    category: 'Web',
    tags: ['React', 'HealthTech', 'Data Viz'],
    desc: 'A patient-facing health dashboard that surfaces actionable insights from complex medical data.',
    img: 'https://images.pexels.com/photos/7089401/pexels-photo-7089401.jpeg?auto=compress&cs=tinysrgb&w=800',
    featured: false,
  },
  {
    id:3,
    title: 'Nova Brand Identity',
    client: 'Nova Ventures',
    category: 'Brand',
    tags: ['Identity', 'Branding', 'Guidelines'],
    desc: 'A bold, modern brand identity for a Series A venture studio entering competitive markets.',
    img: 'https://images.pexels.com/photos/6444/pencil-typography-black-design.jpg?auto=compress&cs=tinysrgb&w=800',
    featured: false,
  },
  {
    id:4,
    title: 'Orbit SaaS Dashboard',
    client: 'Orbit Analytics',
    category: 'Web',
    tags: ['React', 'SaaS', 'Dashboard'],
    desc: 'A complex analytics platform redesigned for clarity, reducing time-to-insight by over 60%.',
    img: 'https://images.pexels.com/photos/590022/pexels-photo-590022.jpeg?auto=compress&cs=tinysrgb&w=800',
    featured: false,
  },
  {
    id:5,
    title: 'Flux Growth Strategy',
    client: 'Flux Technologies',
    category: 'Strategy',
    tags: ['Strategy', 'Roadmap', 'Growth'],
    desc: 'A 12-month digital strategy that helped a B2B SaaS company double its MRR.',
    img: 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=800',
    featured: false,
  },
];

export default projects;